# Generated by Django 5.2.7 on 2026-10-06 04:46

import ckeditor.fields
import course_partnerships.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        ('course_partnerships', '0013_partner_invite_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='donation_button_label',
            field=models.CharField(blank=True, help_text='Leave blank to use "Donate".', max_length=50, verbose_name='Donation button text'),
        ),
        migrations.AddField(
            model_name='partner',
            name='donation_enabled',
            field=models.BooleanField(default=False, help_text="Show a donation card on the course home page of this school's courses.", verbose_name='Show donation card'),
        ),
        migrations.AddField(
            model_name='partner',
            name='donation_excluded_courses',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text="This school's courses that should not show the donation card.", related_name='donation_excluding_partners', to='course_overviews.courseoverview', verbose_name='Courses without donation card'),
        ),
        migrations.AddField(
            model_name='partner',
            name='donation_heading',
            field=models.CharField(blank=True, help_text='Leave blank to use "Support <school name>".', max_length=255, verbose_name='Donation heading'),
        ),
        migrations.AddField(
            model_name='partner',
            name='donation_message',
            field=ckeditor.fields.RichTextField(blank=True, help_text='At most 500 characters of visible text.', null=True, verbose_name='Donation message'),
        ),
        migrations.AddField(
            model_name='partner',
            name='donation_url',
            field=models.URLField(blank=True, help_text="The school's own donation page. Must start with https://.", max_length=500, validators=[course_partnerships.validators.validate_https_url], verbose_name='Donation page URL'),
        ),
        migrations.CreateModel(
            name='DonationClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_clicks', to='course_partnerships.partner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation click',
                'verbose_name_plural': 'Donation clicks',
                'indexes': [models.Index(fields=['partner', 'created'], name='course_part_partner_2c7e32_idx')],
            },
        ),
    ]
