# Generated by Django 5.2.7 on 2026-10-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_partnerships', '0014_partner_donation_fields_donationclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='donation_show_heading',
            field=models.BooleanField(default=True, help_text='Uncheck to show the card without a heading, starting with the message.', verbose_name='Show donation heading'),
        ),
    ]
